{
 "title": "Kubernetes PVC Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "claim",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{cluster=~\"$cluster\", namespace=~\"$namespace\"},persistentvolumeclaim)"
    }
   },
   {
    "name": "interval",
    "query": "5s,10s,15s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"} / on(cluster, instance, namespace, persistentvolumeclaim) kubelet_volume_stats_capacity_bytes",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC Audit Details",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pvc_pvcs_with_wastage{cluster=~\"$cluster\"} \n",
     "legendFormat": "__auto"
    },
    {
     "expr": "pvc_unattached{cluster=~\"$cluster\"} \n",
     "legendFormat": "__auto"
    },
    {
     "expr": "pvc_cleanup_candidates{cluster=~\"$cluster\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pvc_total_pvcs{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pvc_total_namespaces{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Space versus Wasted Space",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  sum(pvc_total_used_gb{cluster=~\"$cluster\"}), \n  \"type\", \"Used Space\", \"__name__\", \".*\"\n)\nor\nlabel_replace(\n  sum(pvc_total_wasted_gb{cluster=~\"$cluster\"}), \n  \"type\", \"Wasted Space\", \"__name__\", \".*\"\n)\nor\nlabel_replace(\n  sum(pvc_total_allocated_gb{cluster=~\"$cluster\"}) \n    - sum(pvc_total_used_gb{cluster=~\"$cluster\"}) \n    - sum(pvc_total_wasted_gb{cluster=~\"$cluster\"}),\n  \"type\", \"Free Space\", \"__name__\", \".*\"\n)\n",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "PVC Summary",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pvc_total_allocated_gb{cluster=~\"$cluster\"})",
     "legendFormat": "Total Allocated Space (GB)"
    },
    {
     "expr": "max(pvc_total_used_gb{cluster=~\"$cluster\"})",
     "legendFormat": "Total Used Space (GB)"
    },
    {
     "expr": "max(pvc_total_wasted_gb{cluster=~\"$cluster\"})\n",
     "legendFormat": "Total Wasted Space (GB)"
    }
   ]
  },
  {
   "title": "📊  PVC Wastage Trend by Percentage  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(5, max by(namespace, persistentvolumeclaim) (\n  100 * (1 - (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes))\n))\n\n",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "📈Namespace Wastage Trend Over Time ",
   "type": "timeseries",
   "description": "How wastage grows or shrinks over time by Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(pvc_namespace_wasted_gb) without(pod, persistentvolumeclaim)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "📊 Top 5 PVCs by Wastage (GB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(\n  5,\n  sum by(namespace, pvc) (\n    max by(namespace, pvc, pvc_name) (pvc_wasted_gb)\n  )\n)\n",
     "legendFormat": "{{namespace}}/{{pvc}}"
    }
   ]
  },
  {
   "title": "Read OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "max by (namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") * on (instance, persistentvolume) group_left(image) label_replace(kube_persistentvolume_info{csi_driver=\"rook-ceph.rbd.csi.ceph.com\"}, \"image\", \"$1\", \"csi_volume_handle\", \"(.*)\") * on (image) group_right(namespace, persistentvolumeclaim) rate(ceph_rbd_read_ops[$__rate_interval]))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Write OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "max by (namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") * on (instance, persistentvolume) group_left(image) label_replace(kube_persistentvolume_info{csi_driver=\"rook-ceph.rbd.csi.ceph.com\"}, \"image\", \"$1\", \"csi_volume_handle\", \"(.*)\") * on (image) group_right(namespace, persistentvolumeclaim) rate(ceph_rbd_write_ops[$__rate_interval]))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by (namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") * on (instance, persistentvolume) group_left(image) label_replace(kube_persistentvolume_info{csi_driver=\"rook-ceph.rbd.csi.ceph.com\"}, \"image\", \"$1\", \"csi_volume_handle\", \"(.*)\") * on (image) group_right(namespace, persistentvolumeclaim) rate(ceph_rbd_read_bytes[$__rate_interval]))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by (namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") * on (instance, persistentvolume) group_left(image) label_replace(kube_persistentvolume_info{csi_driver=\"rook-ceph.rbd.csi.ceph.com\"}, \"image\", \"$1\", \"csi_volume_handle\", \"(.*)\") * on (image) group_right(namespace, persistentvolumeclaim) rate(ceph_rbd_write_bytes[$__rate_interval]))",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by (namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") * on (instance, persistentvolume) group_left(image) label_replace(kube_persistentvolume_info{csi_driver=\"rook-ceph.rbd.csi.ceph.com\"}, \"image\", \"$1\", \"csi_volume_handle\", \"(.*)\") * on (image) group_right(namespace, persistentvolumeclaim) (rate(ceph_rbd_read_latency_sum[$__rate_interval]) / on (instance, image) rate(ceph_rbd_read_latency_count[$__rate_interval])) or kube_persistentvolumeclaim_info{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"} * 0)",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by (namespace, persistentvolumeclaim) (label_replace(kube_persistentvolumeclaim_info{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") * on (persistentvolume) group_left(instance, image) label_replace(kube_persistentvolume_info{csi_driver=\"rook-ceph.rbd.csi.ceph.com\"}, \"image\", \"$1\", \"csi_volume_handle\", \"(.*)\") * on (image) group_right(namespace, persistentvolumeclaim) (rate(ceph_rbd_write_latency_sum[$__rate_interval]) / on (instance, image) rate(ceph_rbd_write_latency_count[$__rate_interval])) or kube_persistentvolumeclaim_info{cluster=~\"$cluster\",namespace=~\"$namespace\",persistentvolumeclaim=~\"$claim\"} * 0)",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}